### ISSUE TITLE
mujoco py install error - fatal error: GL/osmesa.h: No such file or directory

### ISSUE THREAD

**Issue by eastskykang** [ethz-asl/reinmav-gym#35]
during mujoco-py installation, 

```
 /tmp/pip-install-rsxccpmh/mujoco-py/mujoco_py/gl/osmesashim.c:1:23: fatal error: GL/osmesa.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

might appear. 

It can be resolved with 

```sh
$ sudo apt-get install libosmesa6-dev
```

**Comment by eastskykang** [comment]
Need to update README or wiki.

**Comment by tammerb** [comment]
The fix can be found here: https://github.com/openai/mujoco-py#ubuntu-installtion-troubleshooting
`sudo apt install libosmesa6-dev libgl1-mesa-glx libglfw3`

**Comment by SHITIANYU-hue** [comment]
The following packages have unmet dependencies:
 libosmesa6-dev : Depends: libosmesa6 (= 20.0.8-0ubuntu1~18.04.1~ppa1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by SHITIANYU-hue** [comment]
Do you know how to solve this problem? thanks!

**Comment by Jaeyoung-Lim** [comment]
@SHITIANYU-hue You probably have dependency conflicts on your system.
Have you tried installing `libmesa6` directly?

**Comment by SHITIANYU-hue** [comment]
Yes, I downloaded it here: https://launchpad.net/~ubuntu-x-swat/+archive/ubuntu/updates/+build/19465714. 
However, I still have this problem😭

**Comment by robotlearning123** [comment]
Search and install a specific version pkg.
Ref: https://linoxide.com/install-specific-version-package-apt-get/

https://github.com/openai/mujoco-py/issues/96#issuecomment-417897640

**Comment by shivanimall** [comment]
no root access, how to resolve this issue?

**Comment by GoingMyWay** [comment]
How can I install without sudo?

**Comment by mrvgao** [comment]
thanks a lot!!!!!!!!! @eastskykang

**Comment by DouPiChen** [comment]
no root access, how to resolve this issue?

**Comment by qureshinomaan** [comment]
> no root access, how to resolve this issue?

This worked for me : https://github.com/openai/mujoco-py/issues/627#issuecomment-1007658905

**Comment by ZikangXiong** [comment]
> no root access, how to resolve this issue?

This works in my conda environment
```shell
conda install -c conda-forge mesalib glew glfw
```
